import type { Meta, StoryObj } from '@storybook/react-vite'

const colors=['accent-100','accent-300','accent-500','accent-700','accent-900','gray-00','gray-50','gray-100','gray-200','gray-300','gray-500','gray-700','gray-900','gray-950','success-500','warning-500','error-500','info-500','error-500-5']
const semantics={'surface-default':'gray-00','surface-subtle':'gray-50','surface-muted':'gray-100','surface-action-primary':'accent-500','surface-action-primary-hover':'accent-700','surface-action-secondary-hover':'gray-100','surface-action-ghost-hover':'gray-50','surface-success-subtle':'success-500','surface-warning-subtle':'warning-500','surface-error-subtle':'error-500-5','text-default':'gray-900','text-strong':'gray-950','text-muted':'gray-500','text-disabled':'gray-300','text-on-action':'gray-00','text-action':'accent-500','text-success':'success-500','text-warning':'warning-500','text-error':'error-500','border-default':'gray-200','border-strong':'gray-300','border-action':'accent-500','border-focus-ring':'accent-500','border-error':'error-500','bg-success':'success-500','bg-warning':'warning-500','bg-error':'error-500','bg-info':'info-500'} as const
const scales=['size-xs','size-sm','size-base','size-lg','size-xl','size-2xl','size-3xl','size-4xl','weight-regular','weight-medium','weight-semibold','weight-bold','line-height-tight','line-height-base','line-height-loose','tracking-tight','tracking-normal','tracking-wide','radius-none','radius-sm','radius-md','radius-lg','space-1','space-2','space-3','space-4','space-6','space-8','space-12','space-16','shadow-sm','shadow-md','shadow-lg']
const typeStyles=[['ds-heading-4xl','DS/Heading/4xl'],['ds-heading-3xl','DS/Heading/3xl'],['ds-heading-2xl','DS/Heading/2xl'],['ds-heading-xl','DS/Heading/xl'],['ds-heading-lg','DS/Heading/lg'],['ds-body-base','DS/Body/base'],['ds-body-sm','DS/Body/sm'],['ds-body-sm-medium','DS/Body/sm Medium'],['ds-body-xs','DS/Body/xs'],['ds-label-xs','DS/Label/xs']]

function Value({name}:{name:string}){const value=typeof document==='undefined'?'':getComputedStyle(document.documentElement).getPropertyValue(`--${name}`).trim();return <>{value}</>}
function Token({name,reference}:{name:string;reference?:string}){return <article className="sb-token"><div className="sb-token-swatch" style={{background:`var(--${name})`}}/><div className="sb-token-meta"><code>--{name}</code><small>{reference?`→ --${reference}`:<Value name={name}/>}</small></div></article>}
function Foundation(){return <div className="sb-stack"><section className="sb-panel"><h2 className="ds-heading-2xl">Primitive · Colors</h2><div className="sb-token-grid">{colors.map(name=><Token name={name} key={name}/>)}</div></section><section className="sb-panel"><h2 className="ds-heading-2xl">Primitive · Scales</h2><div className="sb-scale">{scales.map(name=><div className="sb-scale-row" key={name}><code>--{name}</code><span><Value name={name}/></span></div>)}</div></section><section className="sb-panel"><h2 className="ds-heading-2xl">Semantic</h2><div className="sb-token-grid">{Object.entries(semantics).map(([name,ref])=><Token name={name} reference={ref} key={name}/>)}</div></section><section className="sb-panel"><h2 className="ds-heading-2xl">Typography</h2><div className="sb-scale">{typeStyles.map(([className,name])=><div className="sb-scale-row" key={name}><code>{name}</code><span className={className}>Сервер готов к работе</span></div>)}</div></section></div>}

/** Все глобальные и смысловые переменные CryptoVPS, прочитанные из CSS tokens. */
const meta={title:'Foundation/Design Tokens',component:Foundation,tags:['autodocs'],parameters:{layout:'padded'}} satisfies Meta<typeof Foundation>
export default meta
type Story=StoryObj<typeof meta>
/** Полный каталог Primitive, Semantic и TextStyles. */
export const AllTokens:Story={}
